# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        #Form.setObjectName("Idioma")
        #Form.resize(304, 183)
        self.__radioButton = QtWidgets.QRadioButton(Form)
        self.__radioButton.setGeometry(QtCore.QRect(50, 40, 82, 17))
        self.__radioButton.setObjectName("radioButton")
        self.__radioButton_2 = QtWidgets.QRadioButton(Form)
        self.__radioButton_2.setGeometry(QtCore.QRect(120, 40, 82, 17))
        self.__radioButton_2.setObjectName("radioButton_2")
        self.__radioButton_3 = QtWidgets.QRadioButton(Form)
        self.__radioButton_3.setGeometry(QtCore.QRect(190, 40, 82, 17))
        self.__radioButton_3.setObjectName("radioButton_3")
        self.__label = QtWidgets.QLabel(Form)
        self.__label.setGeometry(QtCore.QRect(100, 10, 141, 16))
        self.__label.setObjectName("label")
        self.__label_2 = QtWidgets.QLabel(Form)
        self.__label_2.setGeometry(QtCore.QRect(80, 70, 161, 16))
        self.__label_2.setObjectName("label_2")
        self.__comboBox = QtWidgets.QComboBox(Form)
        self.__comboBox.setGeometry(QtCore.QRect(110, 100, 91, 22))
        self.__comboBox.setObjectName("comboBox")
        self.__comboBox.addItem("")
        self.__comboBox.addItem("")
        self.__comboBox.addItem("")
        self.__comboBox.addItem("")
        self.__comboBox.addItem("")
        self.__comboBox.addItem("")
        self.__pushButton = QtWidgets.QPushButton(Form)
        self.__pushButton.setEnabled(False)
        self.__pushButton.setGeometry(QtCore.QRect(120, 140, 75, 23))
        self.__pushButton.setObjectName("pushButton")

        self.__retranslateUi(Form)
        self.__radioButton.clicked['bool'].connect(self.__pushButton.setEnabled) # type: ignore
        self.__radioButton_2.clicked['bool'].connect(self.__pushButton.setEnabled) # type: ignore
        self.__radioButton_3.clicked['bool'].connect(self.__pushButton.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.__radioButton.setText(_translate("Form", "Ingles"))
        self.__radioButton_2.setText(_translate("Form", "Frances"))
        self.__radioButton_3.setText(_translate("Form", " Portugues"))
        self.__label.setText(_translate("Form", "Seleccione su idioma:"))
        self.__label_2.setText(_translate("Form", "Seleccione el mensaje a mostrar:"))
        self.__comboBox.setItemText(0, _translate("Form", "Saludar"))
        self.__comboBox.setItemText(1, _translate("Form", "Despedirse"))
        self.__comboBox.setItemText(2, _translate("Form", "Perdon"))
        self.__comboBox.setItemText(3, _translate("Form", "Pedir cafe"))
        self.__comboBox.setItemText(4, _translate("Form", "Cuanto cuesta"))
        self.__comboBox.setItemText(5, _translate("Form", "Donde queda"))
        self.__pushButton.setText(_translate("Form", "Aceptar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
