from PyQt5 import QtCore, QtWidgets

class Main(object):
    def __init__(self,form):
        super().__init__()
        form.setWindowTitle("Idioma") 
        self.__boton_Ingles = QtWidgets.QRadioButton(form)
        self.__boton_Ingles.setGeometry(QtCore.QRect(50, 40, 82, 17))
        self.__boton_Ingles.setObjectName("boton_Ingles")
        self.__boton_frances = QtWidgets.QRadioButton(form)
        self.__boton_frances.setGeometry(QtCore.QRect(120, 40, 82, 17))
        self.__boton_frances.setObjectName("boton_frances")
        self.__boton_portugues = QtWidgets.QRadioButton(form)
        self.__boton_portugues.setGeometry(QtCore.QRect(190, 40, 82, 17))
        self.__boton_portugues.setObjectName("boton_portugues")
        self.__label = QtWidgets.QLabel(form)
        self.__label.setGeometry(QtCore.QRect(100, 10, 141, 16))
        self.__label.setObjectName("label")
        self.__label_2 = QtWidgets.QLabel(form)
        self.__label_2.setGeometry(QtCore.QRect(80, 70, 161, 16))
        self.__label_2.setObjectName("label_2")
        self.__comboBox = QtWidgets.QComboBox(form)
        self.__comboBox.setGeometry(QtCore.QRect(110, 100, 91, 22))
        self.__comboBox.setObjectName("comboBox")
        self.__comboBox.addItem("")
        self.__comboBox.addItem("")
        self.__comboBox.addItem("")
        self.__comboBox.addItem("")
        self.__comboBox.addItem("")
        self.__comboBox.addItem("")
        self.__aceptar_boton = QtWidgets.QPushButton(form)
        self.__aceptar_boton.setEnabled(False)
        self.__aceptar_boton.setGeometry(QtCore.QRect(120, 140, 75, 23))
        self.__aceptar_boton.setObjectName("aceptar_boton")

        self.texto()
        self.__boton_Ingles.clicked['bool'].connect(self.__aceptar_boton.setEnabled)
        self.__boton_frances.clicked['bool'].connect(self.__aceptar_boton.setEnabled)
        self.__boton_portugues.clicked['bool'].connect(self.__aceptar_boton.setEnabled)

    def texto(self):
        self.__boton_Ingles.setText("Ingles")
        self.__boton_frances.setText("Frances")
        self.__boton_portugues.setText("Portugues")
        self.__label.setText("Seleccione su idioma:")
        self.__label_2.setText("Seleccione el mensaje a mostrar:")
        self.__comboBox.setItemText(0,"Saludar")
        self.__comboBox.setItemText(1,"Despedirse")
        self.__comboBox.setItemText(2,"Perdón")
        self.__comboBox.setItemText(3,"Pedir café")
        self.__comboBox.setItemText(4,"¿Cuánto cuesta?")
        self.__comboBox.setItemText(5,"¿Dónde queda?")
        self.__aceptar_boton.setText("Aceptar")
    